const More = (props: { className?: string }) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width={21}
    height={20}
    fill="none"
    className={props.className}
    {...props}>
    <circle
      cx={2.504}
      cy={10}
      r={2.5}
      fill="currentColor"
    />
    <circle
      cx={10.004}
      cy={10}
      r={2.5}
      fill="currentColor"
    />
    <circle
      cx={17.504}
      cy={10}
      r={2.5}
      fill="currentColor"
    />
  </svg>
);
export default More;
